# Generated by Django 5.0.7 on 2024-07-21 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Loja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=20, verbose_name='Nome Da Loja')),
                ('numero', models.IntegerField(max_length=9, verbose_name='Número de Tel')),
            ],
        ),
    ]
