# Generated by Django 5.0.7 on 2024-07-21 14:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminDashboard', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Servico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=20, verbose_name='Nome Do Serviço')),
                ('descricao', models.CharField(max_length=20, verbose_name='Descrição Do Serviço')),
                ('img', models.ImageField(blank=True, null=True, upload_to='servico/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'png', 'jpeg'])], verbose_name='Foto do Serviço')),
            ],
        ),
    ]
