# Generated by Django 5.0.7 on 2024-07-22 11:11

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminDashboard', '0002_servico'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=20, verbose_name='Nome Completo')),
                ('endereco', models.CharField(max_length=20, verbose_name='Endereço')),
                ('numero', models.CharField(max_length=9, verbose_name='Numero de Tel')),
                ('genero', models.CharField(choices=[('M', 'Masculino'), ('F', 'Feminino')], max_length=2, verbose_name='Genero')),
                ('dataNasc', models.DateField(verbose_name='Data de Nascimento')),
                ('img', models.ImageField(blank=True, null=True, upload_to='cli/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'png', 'jpeg'])], verbose_name='Foto do Serviço')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cliUsuario', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
        ),
        migrations.CreateModel(
            name='Funcionario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=20, verbose_name='Nome Completo')),
                ('endereco', models.CharField(max_length=20, verbose_name='Endereço')),
                ('numero', models.CharField(max_length=9, verbose_name='Numero de Tel')),
                ('genero', models.CharField(choices=[('M', 'Masculino'), ('F', 'Feminino')], max_length=9, verbose_name='Genero')),
                ('img', models.ImageField(blank=True, null=True, upload_to='func/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'png', 'jpeg'])], verbose_name='Foto do Serviço')),
                ('loja', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loja', to='AdminDashboard.loja', verbose_name='Loja')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='funcUsuario', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
        ),
    ]
