# Generated by Django 5.0.7 on 2024-07-22 11:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UserAutenticacao', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='profile_foto',
        ),
    ]
