# Generated by Django 5.0.7 on 2024-07-25 22:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UserAutenticacao', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='usuario',
            table='Usuario',
        ),
    ]
