# Generated by Django 5.0.7 on 2024-07-31 15:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('FuncDashboard', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=20, verbose_name='Nome Completo')),
                ('endereco', models.CharField(max_length=20, null=True, verbose_name='Endereço')),
                ('email', models.EmailField(max_length=254)),
                ('numero', models.CharField(max_length=9, null=True, verbose_name='Número de Tel')),
                ('genero', models.CharField(choices=[('M', 'Masculino'), ('F', 'Feminino')], max_length=2, verbose_name='Genero')),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
                'db_table': 'Cliente',
            },
        ),
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_reserva', models.DateField(auto_now_add=True)),
                ('total', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('estado', models.BooleanField(default=False)),
                ('data_entrada', models.DateField(null=True)),
                ('data_saida', models.DateField(null=True)),
                ('codigo_reserva', models.CharField(editable=False, max_length=10, unique=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Portifolio.cliente')),
                ('funcionario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='func', to='FuncDashboard.funcionario')),
            ],
            options={
                'verbose_name': 'Reserva',
                'verbose_name_plural': 'Reservas',
                'db_table': 'Reserva',
            },
        ),
        migrations.CreateModel(
            name='ServicosReservado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qtd', models.IntegerField()),
                ('subtotal', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('reserva', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reserva', to='Portifolio.reserva')),
                ('servico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='servico', to='FuncDashboard.servico')),
            ],
            options={
                'verbose_name': 'ServicoReservado',
                'verbose_name_plural': 'ServicoReservados',
                'db_table': 'ServicoReservado',
            },
        ),
    ]
