# Generated by Django 5.0.7 on 2024-07-24 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Portifolio', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='numero',
            field=models.CharField(max_length=9, null=True, verbose_name='Número de Tel'),
        ),
    ]
