# Generated by Django 5.0.7 on 2024-07-31 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Portifolio', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='cliente',
            unique_together={('email', 'numero')},
        ),
    ]
