# Generated by Django 5.0.7 on 2024-07-24 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Portifolio', '0002_alter_pedido_estado'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cliente',
            options={'verbose_name': 'Cliente', 'verbose_name_plural': 'Clientes'},
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='dataNasc',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='img',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='usuario',
        ),
        migrations.RemoveField(
            model_name='itempedido',
            name='qtd',
        ),
        migrations.RemoveField(
            model_name='pedido',
            name='loja',
        ),
        migrations.AddField(
            model_name='pedido',
            name='qtd',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='pedido',
            name='data_pedido',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='estado',
            field=models.BooleanField(),
        ),
    ]
