"""
Django settings for AzulClaros project.

Generated by 'django-admin startproject' using Django 5.0.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""

from pathlib import Path
import environ
import os
from django.urls import reverse


# Initialise environment variables
env = environ.Env()
environ.Env.read_env()



# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-rzlb9#@v(&5q#%m@&j#248g&+y&ql27zk=mr9dtj@j8v=4)4k8'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'jazzmin',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'Portifolio',
    'FuncDashboard',
    'UserAutenticacao',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'AzulClaros.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR),'template'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'AzulClaros.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': env('DB_NAME'),
        'USER': env('DB_USER'),
        'PASSWORD': env('DB_PASSWORD'),
        'HOST': env('DB_HOST'),
        'PORT': '3306'
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

AUTHENTICATION_BACKENDS = [
    'django.contrib.auth.backends.ModelBackend',  # Backend padrão
    'UserAutenticacao.backends.EmailBackend',  # backend personalizado
]

# Internationalization
# https://docs.djangoproject.com/en/5.0/topics/i18n/

LANGUAGE_CODE = 'pt-br'

TIME_ZONE = 'Africa/Luanda'

USE_I18N = True

USE_I10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.0/howto/static-files/

STATIC_URL = '/static/'
STATICFILES_DIRS=[os.path.join(BASE_DIR,'static')]
STATIC_ROOT=os.path.join(BASE_DIR,'staticfiles')

MEDIA_URL = '/media/'
MEDIAFILES_DIRS = [os.path.join(BASE_DIR,'mediafiles')]
MEDIA_ROOT = os.path.join(BASE_DIR,'media')

# Default primary key field type
# https://docs.djangoproject.com/en/5.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

AUTH_USER_MODEL = 'UserAutenticacao.Usuario'

# Configurações do Jazzmin
JAZZMIN_SETTINGS = {
    'site_title': 'Azul Claros',
    'site_header': 'Painel Administrativo',
    'site_brand': 'Azul Claros',
    'welcome_sign': 'Bem-vindo ao Painel de Administração da Azul Claros',
    'copyright': 'Azul Claros',
    'topmenu_links': [  
        # Outros links...  
        {"name": "Relactorios", "url": "/relatorio/", 
            'permissions': ['is_authenticated'],
            "icon": "fas fa-newspaper"},  # Adicione aqui  
    ],
    'search_model': 'UserAutenticacao.Usuario',
    'user_avatar': None,
    'show_sidebar': True,
    'navigation_expanded': True,
    'order_with_respect_to': ['UserAutenticacao', 'Usuario'],
    'icons': {
        'UserAutenticacao': 'fas fa-users-cog',
        'UserAutenticacao.Usuario': 'fas fa-user',
        'auth.Group': 'fas fa-users',
        'FuncDashboard.Funcionario': 'fas fa-user-tie',
        'FuncDashboard.Reserva': 'fas fa-address-book',
        'FuncDashboard.Servico': 'fas fa-shopping-cart',
        'FuncDashboard.Cliente': 'fas fa-check-square',
        'FuncDashboard.MetodoPagamento': 'fas fa-credit-card',
        'FuncDashboard.Pagamentos': 'fas fa fa-money',
        'FuncDashboard.Feedback': 'fas fa-comments',
        'FuncDashboard.ReservaEstatistica': 'fas fa fa-signal',
        'FuncDashboard.Sobre': 'fas fa fa-sticky-note',
        'FuncDashboard.ServicosReservado': 'fas fa-cart-plus',
    },
    'default_icon_parents': 'fas fa-chevron-circle-right',
    'default_icon_children': 'fas fa-circle',
    'related_modal_active': False,
    'custom_css': None,
    'custom_js': None,
    'show_ui_builder': False,
    
}
LOGOUT_REDIRECT_URL = 'login'

#CONFIGURAÇÂO DE EMAIL
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587
EMAIL_USE_TLS = True
DEFAULT_EMAIL_FROM = 'Azul Claros - Lavandaria'
EMAIL_HOST_USER = 'benartur.ab@gmail.com'
EMAIL_HOST_PASSWORD = 'nvanhlgtygodaddd'