# Generated by Django 5.0.7 on 2024-08-03 01:57

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Funcionario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=20, verbose_name='Nome Completo')),
                ('endereco', models.CharField(max_length=20, verbose_name='Endereço')),
                ('numero', models.CharField(max_length=9, verbose_name='Número de Tel')),
                ('genero', models.CharField(choices=[('M', 'Masculino'), ('F', 'Feminino')], max_length=9, verbose_name='Genero')),
                ('img', models.ImageField(blank=True, null=True, upload_to='Func/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'png', 'jpeg'])], verbose_name='Foto do Serviço')),
            ],
            options={
                'verbose_name': 'Funcionario',
                'verbose_name_plural': 'Funcionarios',
                'db_table': 'Funcionario',
            },
        ),
        migrations.CreateModel(
            name='MetodoPagamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metodo', models.CharField(max_length=10)),
            ],
            options={
                'verbose_name': 'Metodo de Pagamento',
                'verbose_name_plural': 'Metodos de Pagamentos',
                'db_table': 'MetodoPagamento',
            },
        ),
        migrations.CreateModel(
            name='Pagamentos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('dataPagamento', models.DateField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Pagamento',
                'verbose_name_plural': 'Pagamentos',
                'db_table': 'Pagamento',
            },
        ),
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_reserva', models.DateField(auto_now_add=True)),
                ('total', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('estado', models.IntegerField(default=0, max_length=1)),
                ('data_entrada', models.DateField(null=True)),
                ('data_saida', models.DateField(null=True)),
                ('obs', models.TextField(null=True)),
                ('codigo_reserva', models.CharField(editable=False, max_length=10, unique=True)),
            ],
            options={
                'verbose_name': 'Reserva',
                'verbose_name_plural': 'Reservas',
                'db_table': 'Reserva',
            },
        ),
        migrations.CreateModel(
            name='Servico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=20, verbose_name='Nome Do Serviço')),
                ('descricao', models.TextField(verbose_name='Descrição Do Serviço')),
                ('preco', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Descrição Do Serviço')),
                ('img', models.ImageField(blank=True, null=True, upload_to='servico/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'png', 'jpeg'])], verbose_name='Foto do Serviço')),
            ],
            options={
                'verbose_name': 'Serviço',
                'verbose_name_plural': 'Serviços',
                'db_table': 'Servico',
            },
        ),
        migrations.CreateModel(
            name='ServicosReservado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qtd', models.IntegerField()),
                ('subtotal', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
            ],
            options={
                'verbose_name': 'ServicoReservado',
                'verbose_name_plural': 'ServicoReservados',
                'db_table': 'ServicoReservado',
            },
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=20, verbose_name='Nome Completo')),
                ('endereco', models.CharField(max_length=20, null=True, verbose_name='Endereço')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('numero', models.CharField(max_length=9, null=True, verbose_name='Número de Tel')),
                ('genero', models.CharField(choices=[('M', 'Masculino'), ('F', 'Feminino')], max_length=2, verbose_name='Genero')),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
                'db_table': 'Cliente',
                'unique_together': {('email', 'numero')},
            },
        ),
    ]
