# Generated by Django 5.0.7 on 2024-07-23 18:16

import django.core.validators
import django.db.models.deletion
import phonenumber_field.modelfields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Loja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=20, verbose_name='Nome Da Loja')),
                ('numero', phonenumber_field.modelfields.PhoneNumberField(max_length=9, region='AO', verbose_name='Número de Tel')),
            ],
        ),
        migrations.CreateModel(
            name='Servico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=20, verbose_name='Nome Do Serviço')),
                ('descricao', models.CharField(max_length=20, verbose_name='Descrição Do Serviço')),
                ('img', models.ImageField(blank=True, null=True, upload_to='servico/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'png', 'jpeg'])], verbose_name='Foto do Serviço')),
            ],
        ),
        migrations.CreateModel(
            name='Funcionario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=20, verbose_name='Nome Completo')),
                ('endereco', models.CharField(max_length=20, verbose_name='Endereço')),
                ('numero', phonenumber_field.modelfields.PhoneNumberField(max_length=9, region='AO', verbose_name='Número de Tel')),
                ('genero', models.CharField(choices=[('M', 'Masculino'), ('F', 'Feminino')], max_length=9, verbose_name='Genero')),
                ('img', models.ImageField(blank=True, null=True, upload_to='func/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'png', 'jpeg'])], verbose_name='Foto do Serviço')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='funcUsuario', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
                ('loja', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loja', to='FuncDashboard.loja', verbose_name='Loja')),
            ],
        ),
    ]
