# Generated by Django 5.1 on 2024-08-31 21:31

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Funcionario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=20, verbose_name='Nome Completo')),
                ('endereco', models.CharField(max_length=20, verbose_name='Endereço')),
                ('numero', models.CharField(max_length=9, verbose_name='Número de Tel')),
                ('genero', models.CharField(choices=[('M', 'Masculino'), ('F', 'Feminino')], max_length=9, verbose_name='Genero')),
                ('img', models.ImageField(blank=True, null=True, upload_to='Func/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'png', 'jpeg'])], verbose_name='Foto do Serviço')),
            ],
            options={
                'verbose_name': 'Funcionario',
                'verbose_name_plural': 'Funcionarios',
                'db_table': 'Funcionario',
            },
        ),
        migrations.CreateModel(
            name='MetodoPagamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metodo', models.CharField(max_length=10)),
            ],
            options={
                'verbose_name': 'Metodo de Pagamento',
                'verbose_name_plural': 'Metodos de Pagamentos',
                'db_table': 'MetodoPagamento',
            },
        ),
        migrations.CreateModel(
            name='Pagamentos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('dataPagamento', models.DateField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Pagamento',
                'verbose_name_plural': 'Pagamentos',
                'db_table': 'Pagamento',
            },
        ),
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_reserva', models.DateField(auto_now_add=True)),
                ('total', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('estado', models.IntegerField(default=0, max_length=1)),
                ('data_entrada', models.DateField(null=True)),
                ('data_saida', models.DateField(null=True)),
                ('obs', models.TextField(blank=True, null=True)),
                ('codigo_reserva', models.CharField(editable=False, max_length=10, unique=True)),
            ],
            options={
                'verbose_name': 'Reserva',
                'verbose_name_plural': 'Reservas',
                'db_table': 'Reserva',
            },
        ),
        migrations.CreateModel(
            name='ReservaEstatistica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mes', models.DateField()),
                ('estado', models.IntegerField()),
                ('quantidade', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Estatística de Reserva',
                'verbose_name_plural': 'Estatísticas de Reservas',
                'db_table': 'reserva_estatistica',
            },
        ),
        migrations.CreateModel(
            name='Servico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=20, verbose_name='Nome Do Serviço')),
                ('descricao', models.TextField(verbose_name='Descrição Do Serviço')),
                ('preco', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Descrição Do Serviço')),
                ('img', models.ImageField(blank=True, default='', null=True, upload_to='servico/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'png', 'jpeg'])], verbose_name='Foto do Serviço')),
            ],
            options={
                'verbose_name': 'Serviço',
                'verbose_name_plural': 'Serviços',
                'db_table': 'Servico',
            },
        ),
        migrations.CreateModel(
            name='ServicosReservado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qtd', models.IntegerField()),
                ('subtotal', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
            ],
            options={
                'verbose_name': 'Serviço Reservado',
                'verbose_name_plural': 'Serviços Reservados',
                'db_table': 'ServicoReservado',
            },
        ),
        migrations.CreateModel(
            name='Sobre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(default='Sobre a Empresa', max_length=20, verbose_name='Título')),
                ('descricao', models.TextField(default='Somos uma lavandaria com um sistema totalmente diferenciado no mercado angolano, a maior parte das lavandarias no país, o que elas fazem não é serviço de lavandaria, mas de tinturaria, Pois oferecemos serviços de lavagem, secagem e engomagem de forma conjunta bem como segregada, por intermédio de cestos de roupas tu consegues fazer a lavagem, secagem ou engomagem de suas roupas em nossas lavandaria.Aqui a lavagem é feita em quantidade, pois acreditamos que o custo de lavagem de produção de uma única lavagem é o mesmo em quantidade.', max_length=20, verbose_name='Descrição')),
            ],
            options={
                'verbose_name': 'Sobre',
                'verbose_name_plural': 'Sobre',
                'db_table': 'Sobre',
            },
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=20, verbose_name='Nome Completo')),
                ('endereco', models.CharField(max_length=20, null=True, verbose_name='Endereço')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('numero', models.CharField(max_length=9, null=True, verbose_name='Número de Tel')),
                ('genero', models.CharField(choices=[('M', 'Masculino'), ('F', 'Feminino')], max_length=2, verbose_name='Genero')),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
                'db_table': 'Cliente',
                'unique_together': {('email', 'numero')},
            },
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avaliacao', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], verbose_name='Avaliação (1 a 5)')),
                ('comentario', models.TextField(blank=True, null=True, verbose_name='Comentário')),
                ('data', models.DateTimeField(auto_now_add=True, verbose_name='Data do Feedback')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FuncDashboard.cliente')),
            ],
            options={
                'verbose_name': 'Feedback',
                'verbose_name_plural': 'Feedbacks',
                'db_table': 'Feedback',
            },
        ),
    ]
