# Generated by Django 5.0.7 on 2024-08-03 01:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('FuncDashboard', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='funcionario',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario'),
        ),
        migrations.AddField(
            model_name='pagamentos',
            name='metodoPagamento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FuncDashboard.metodopagamento'),
        ),
        migrations.AddField(
            model_name='reserva',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FuncDashboard.cliente'),
        ),
        migrations.AddField(
            model_name='reserva',
            name='funcionario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='func', to='FuncDashboard.funcionario'),
        ),
        migrations.AddField(
            model_name='pagamentos',
            name='reserva',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FuncDashboard.reserva'),
        ),
        migrations.AddField(
            model_name='servicosreservado',
            name='reserva',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reserva', to='FuncDashboard.reserva'),
        ),
        migrations.AddField(
            model_name='servicosreservado',
            name='servico',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='servico', to='FuncDashboard.servico'),
        ),
    ]
