# Generated by Django 5.0.7 on 2024-07-25 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FuncDashboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='funcionario',
            name='numero',
            field=models.CharField(max_length=9, verbose_name='Número de Tel'),
        ),
    ]
