# Generated by Django 5.0.8 on 2024-08-06 20:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FuncDashboard', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sobre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(default='Sobre a Empresa', max_length=20, verbose_name='Título')),
                ('descricao', models.TextField(default='Somos uma lavandaria com um sistema totalmente diferenciado no mercado angolano, a maior parte das lavandarias no país, o que elas fazem não é serviço de lavandaria, mas de tinturaria, Pois oferecemos serviços de lavagem, secagem e engomagem de forma conjunta bem como segregada, por intermédio de cestos de roupas tu consegues fazer a lavagem, secagem ou engomagem de suas roupas em nossas lavandaria.Aqui a lavagem é feita em quantidade, pois acreditamos que o custo de lavagem de produção de uma única lavagem é o mesmo em quantidade.', max_length=20, verbose_name='Descrição')),
            ],
            options={
                'verbose_name': 'Sobre',
                'verbose_name_plural': 'Sobres',
                'db_table': 'Sobre',
            },
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avaliacao', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], verbose_name='Avaliação (1 a 5)')),
                ('comentario', models.TextField(blank=True, null=True, verbose_name='Comentário')),
                ('data', models.DateTimeField(auto_now_add=True, verbose_name='Data do Feedback')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FuncDashboard.cliente')),
                ('reserva', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FuncDashboard.reserva')),
            ],
            options={
                'verbose_name': 'Feedback',
                'verbose_name_plural': 'Feedbacks',
                'db_table': 'Feedback',
            },
        ),
    ]
