# Generated by Django 5.0.7 on 2024-07-24 00:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FuncDashboard', '0002_remove_funcionario_loja_alter_funcionario_options_and_more'),
        ('Portifolio', '0003_alter_cliente_options_remove_cliente_datanasc_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='funcionario',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario'),
        ),
        migrations.DeleteModel(
            name='Loja',
        ),
    ]
