# Generated by Django 5.1 on 2024-08-27 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FuncDashboard', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReservaEstatistica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mes', models.DateField()),
                ('estado', models.IntegerField()),
                ('quantidade', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Estatística de Reserva',
                'verbose_name_plural': 'Estatísticas de Reservas',
                'db_table': 'reserva_estatistica',
                'unique_together': {('mes', 'estado')},
            },
        ),
    ]
