# Generated by Django 5.1 on 2024-09-05 08:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FuncDashboard', '0003_alter_reservaestatistica_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='funcionario',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='Func/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'png', 'jpeg'])], verbose_name='Foto do Funcionario'),
        ),
        migrations.AlterField(
            model_name='servico',
            name='img',
            field=models.ImageField(blank=True, default='', null=True, upload_to='Servicos/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'png', 'jpeg'])], verbose_name='Foto do Serviço'),
        ),
    ]
