# Generated by Django 5.1 on 2024-08-28 09:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FuncDashboard', '0003_reservaestatistica'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservaestatistica',
            name='funcionario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='FuncDashboard.funcionario', verbose_name='Funcionario'),
        ),
    ]
