# Generated by Django 5.0.8 on 2024-08-08 11:54

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FuncDashboard', '0003_sobre_feedback'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servico',
            name='img',
            field=models.ImageField(blank=True, default='', null=True, upload_to='servico/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'png', 'jpeg'])], verbose_name='Foto do Serviço'),
        ),
    ]
